apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: vfuvxvc92-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-494a4a70f1.ka8f.p3.openshiftapps.com/rhtap/rhtap-qe:7a9de829143bceb7e8cfcb4f85be3fa44b0e837d@sha256:0e73932917301ee647ec4a54499aa8c685cd101afd32c62b4a4a31fcc58fb0b3
        name: container-image  
