apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vfuvxvc92-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vfuvxvc92-java-quarkus-gitops